//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassRegistrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRequest
    {
        public int LoginId { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string LoginName { get; set; }
        public string NewOrReactivate { get; set; }
        public string ReasonForAccess { get; set; }
        public Nullable<System.DateTime> DateRequiredBy { get; set; }
    }
}
