//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassRegistrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClassesByStudent
    {
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public System.DateTime ClassDate { get; set; }
        public string ClassDescription { get; set; }
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
    }
}
